### ISSUE TITLE
Use ReactorCraft's Radiation Effect Crash

### ISSUE THREAD

**Issue by ZHENGLOC** [Zoko061602/GregMetTic#2]
Attack Mob crash

https://paste.ubuntu.com/p/qNGmYn7b8r/

**Comment by dieflemm** [comment]
Attacked a mob and got this crash too but used poison (id19), using a negative value to target player works on hit.

Crash report - https://pastebin.com/DwmQmt9T 
( I:Amplifier=1; I:Duration=200; I:Effect=19; I:Probability=1) (-19 works on player)
